### PR TITLE
Fix defaults when options are false'ish

### PR DESCRIPTION
**Pull request by tobias-**
When options are false'ish, the default will be used.

This works poorly for numbers and booleans.

~A temporary workaround for deleteOriginals is to counterintuitively set it to 1.~

### CODE REVIEW

**Comment by TomDeBacker** [comment]
thanks tobias

**Comment by tobias-** [comment]
Thanks yourself for a damn quick merge & release!

Best Regards
/Tobias

**Comment by TomDeBacker** [comment]
@tobias- You having any "JavaScript heap out of memory" issues with the plugin? Unsure if it's just my computer..

**Comment by tobias-** [comment]
I always lock versions, so revert the changes if they break something for you, and let me know if I can help you test, but I'll stick with 0.2.1 until you ask me to test/tell me it's fixed.

**Comment by TomDeBacker** [comment]
I'm using this config: 

`new HTMLCompressionPlugin({
		testHTML: /\.html$/,
		test: /.*\.(css|js)$/i,
		deleteOriginals: true,
		assetsRelativeOutputDirectory: '../../build/public',
		asset: '[path].gz',
		algorithm: 'gzip',
		threshold: 0,
		minRatio: 0.0
	})`

On version 0.2.0 works fine.. 0.2.2 breaks it..

**Pull request merged**
